version: "3.7"

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: {{** CHANGE ME **}}
    image: 'mongo'
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongo
    environment:
      API_SECRET: {{** CHANGE ME **}}
      BASE_URL: {{** CHANGE ME **}}
      MONGO_CONNECTION: "mongodb://admin:{{** CHANGE ME **}}@mongo/admin"
    image: gabe565/nightscout
    links:
      - mongo
    ports:
      - 1337:1337

volumes:
  db:
