version: "3.7"

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeme
    image: 'mongo'
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongo
    environment:
      API_SECRET: changeme
      BASE_URL: changeme
      MONGO_CONNECTION: "mongodb://admin:changeme@mongo/admin"
    image: ghcr.io/gabe565/nightscout
    links:
      - mongo
    ports:
      - 1337:1337

volumes:
  db:
