name: Build

on:
  push: {}

env:
  NIGHTSCOUT_REPO: nightscout/cgm-remote-monitor
  NIGHTSCOUT_REF: 14.2.6

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/gabe565/nightscout
          tags: |
            type=raw,priority=1000,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=semver,pattern={{version}},value=${{ env.NIGHTSCOUT_REF }},enable=${{ github.ref == 'refs/heads/main' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.NIGHTSCOUT_REF }},enable=${{ github.ref == 'refs/heads/main' }}
            type=semver,pattern={{major}},value=${{ env.NIGHTSCOUT_REF }},enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: ${{ github.secret_source == 'Actions' }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NIGHTSCOUT_REPO=${{ env.NIGHTSCOUT_REPO }}
            NIGHTSCOUT_REF=${{ env.NIGHTSCOUT_REF }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
