name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NIGHTSCOUT_REPO: nightscout/cgm-remote-monitor
  NIGHTSCOUT_REF: v15.0.6

jobs:
  build:
    name: Build (${{ matrix.flavor }})
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - suffix: ''
            flavor: base
          - suffix: -websocket
            flavor: websocket
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          flavor: |
            suffix=${{ matrix.suffix }},onlatest=true
          images: ghcr.io/gabe565/nightscout
          tags: |
            type=raw,priority=1000,value=latest
            type=semver,pattern={{version}},value=${{ env.NIGHTSCOUT_REF }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.NIGHTSCOUT_REF }}
            type=semver,pattern={{major}},value=${{ env.NIGHTSCOUT_REF }}
          labels: |
            org.opencontainers.image.title=Nightscout
            maintainer=gabe565
            org.opencontainers.image.vendor=gabe565
            org.opencontainers.image.description=Web-based CGM (Continuous Glucose Monitor) to allow multiple caregivers to remotely view a patient's glucose data in real time
            org.opencontainers.image.source=https://github.com/${{ env.NIGHTSCOUT_REPO }}
            org.opencontainers.image.version=${{ env.NIGHTSCOUT_REF }}
            org.opencontainers.image.licenses=AGPL-3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NIGHTSCOUT_REPO=${{ env.NIGHTSCOUT_REPO }}
            NIGHTSCOUT_REF=${{ env.NIGHTSCOUT_REF }}
            FLAVOR=${{ matrix.flavor }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
