name: Docker Build

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches: master

env:
  image: gabe565/nightscout
  nightscout_release: "14.0.7"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/386,linux/amd64
          tags: |
            ${{ env.image }}:${{ env.nightscout_release }}
            ${{ env.image }}:latest

  readme:
    name: Update DockerHub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.image }}
